spring:
  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    org.springframework.security: INFO

jwt:
  secret: "change-me-to-a-256-bit-secret-string"
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui
    try-it-out-enabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
